'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'

export default function Write(){
 const [profile,setProfile]=useState<any>(null); const [title,setTitle]=useState(''); const [summary,setSummary]=useState(''); const [sport,setSport]=useState('NFL'); const [body,setBody]=useState(''); const [cover,setCover]=useState<File|null>(null); const [busy,setBusy]=useState(false); const supabase=createClient(); const router=useRouter()
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {data}=await supabase.from('profiles').select('*').eq('id',user.id).single(); setProfile(data)})()},[])
 async function publish(e:React.FormEvent){e.preventDefault(); if(!profile)return; if(!['writer','editor','admin','owner'].includes(profile.role)||profile.approval_status!=='approved')return alert('An admin must approve your writer access first.'); setBusy(true); let cover_url=null
  if(cover){const path=`${profile.id}/${crypto.randomUUID()}-${cover.name}`; const {error}=await supabase.storage.from('article-media').upload(path,cover); if(error){setBusy(false);return alert(error.message)} cover_url=supabase.storage.from('article-media').getPublicUrl(path).data.publicUrl}
  const slug=title.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString().slice(-5); const {error}=await supabase.from('articles').insert({author_id:profile.id,title,summary,sport,body,cover_url,slug,status:'published',published_at:new Date().toISOString()}); setBusy(false); if(error)return alert(error.message); router.push(`/article/${slug}`)
 }
 if(profile && (!['writer','editor','admin','owner'].includes(profile.role)||profile.approval_status!=='approved')) return <main className="shell"><div className="formCard"><div className="eyebrow">Publishing access</div><h1>Writer approval required</h1><p className="muted">Your account can use The Bar, but an admin must approve you before you can publish stories in The Press Box.</p></div></main>
 return <main className="shell"><form className="formCard" onSubmit={publish}><div className="eyebrow">Writer studio</div><h1>Write an article</h1><div className="fieldGroup"><label>Headline</label><input className="field" value={title} onChange={e=>setTitle(e.target.value)} required/></div><div className="fieldGroup"><label>Summary</label><textarea className="field" value={summary} onChange={e=>setSummary(e.target.value)} required/></div><div className="row"><div className="fieldGroup" style={{flex:1}}><label>Sport</label><select className="field" value={sport} onChange={e=>setSport(e.target.value)}><option>NFL</option><option>NBA</option><option>NHL</option><option>MLB</option><option>College Football</option><option>College Basketball</option><option>Fantasy</option><option>Other</option></select></div><div className="fieldGroup" style={{flex:1}}><label>Cover image</label><input className="field" type="file" accept="image/*" onChange={e=>setCover(e.target.files?.[0]||null)}/></div></div><div className="fieldGroup"><label>Article</label><textarea className="field textarea" value={body} onChange={e=>setBody(e.target.value)} required/></div><button className="primary" disabled={busy}>{busy?'Publishing…':'Publish article'}</button></form></main>
}
